export default [
  {
    id: 11,
    name: 'Входные взрослый',
    description: '',
    price: 250,
    imgUrl: null,
  },
  {
    id: 12,
    name: 'Входные детский',
    description: '',
    price: 0,
    imgUrl: null,
  },
  {
    id: 13,
    name: 'Иван Чай',
    description: '',
    price: 180,
    imgUrl: null,
  },
  {
    id: 14,
    name: 'Варенье',
    description: '',
    price: 250,
    imgUrl: null,
  },
  {
    id: 15,
    name: 'Мыло на козьем молоке',
    description: '',
    price: 150,
    imgUrl: null,
  },
  {
    id: 10,
    name: 'Мясо бройлера',
    description: '1кг.',
    price: 350,
    imgUrl: require('../resources/images/chicken.jpg'),
    category: '1',
  },
  {
    id: 1,
    name: 'Мясо утки',
    description: '1кг.',
    price: 400,
    imgUrl: require('../resources/images/utka.png'),
    category: '1',
  },
  {
    id: 2,
    name: 'Мясо цесарки',
    description: '1кг.',
    price: 750,
    imgUrl: require('../resources/images/cesarka.png'),
    category: '1',
  },
  {
    id: 3,
    name: 'Мясо гуся',
    description: '1 кг.',
    price: 600,
    imgUrl: require('../resources/images/goose.png'),
    category: '1',
  },
  {
    id: 4,
    name: 'Молоко козье',
    description: '1л.',
    price: 170,
    imgUrl: require('../resources/images/goat_milk.jpg'),
    category: '2',
  },
  {
    id: 5,
    name: 'Сыр козий',
    description: '100гр.',
    price: 150,
    imgUrl: require('../resources/images/cheese1.jpg'),
    category: '2',
  },
  {
    id: 6,
    name: 'Яйца куриные',
    description: '10 шт.',
    price: 150,
    imgUrl: require('../resources/images/eggs1.jpg'),
    category: '3',
  },
  {
    id: 7,
    name: 'Яйца утиные',
    description: '10 шт.',
    price: 200,
    imgUrl: require('../resources/images/duck_eggs1.jpg'),
    category: '3',
  },
  {
    id: 8,
    name: 'Яйца цесариные',
    description: '10 шт.',
    price: 220,
    imgUrl: require('../resources/images/cesarka_eggs1.jpg'),
    category: '3',
  },
];
